;;;; fs-utils.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'fs-utils
      'fs-utils
      (scheme#list)
      '((path . fs-utils#path)
        (dir-contents . fs-utils#dir-contents)
        (dir-dirs . fs-utils#dir-dirs)
        (dir-files . fs-utils#dir-files)
        (directory? . fs-utils#directory?)
        (file? . fs-utils#file?))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
