;;;; fs-utils.import.scm - GENERATED BY CHICKEN 5.2.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'fs-utils
      'fs-utils
      (scheme#list)
      '((* . scheme#*))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
